run:
  timeout: 10m
  modules-download-mode: vendor
linters:
  disable-all: true
  enable:
    - whitespace
    - bodyclose
    - dupl
    - errcheck
    - gci
    - gofmt
    - goimports
    - misspell
    - unused
    - typecheck
    - staticcheck
    - gosimple
    - govet
    - ineffassign
    - typecheck
    - gosec
linters-settings:
  goimports:
    local-prefixes: github.com/kosmos.io/eps-probe-plugin
  misspell:
    ignore-words:
      - creater
  gci:
    sections:
      - Standard
      - Default
      - Prefix(github.com/kosmos.io/eps-probe-plugin)
output:
  sort-results: true




